export const PAIN_RADAR_LIMITS = {
  MAX_POSTS_PER_SCAN: 100,
  MAX_POSTS_PER_ANALYSIS: 50,
  MAX_BATCH_SIZE: 10,
  SCAN_TIMEOUT_MS: 60000,
  AI_TIMEOUT_MS: 30000,
} as const

export const SIMILARITY_THRESHOLD = 0.5
export const CONFIDENCE_THRESHOLD = 0.7
